---
title: "AS4"
author: "YinxuanHuang"
date: '2023-01-08'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,message = F,warning = F,fig.align = "center")
```

## Loading library

```{r}
library(ggplot2)
library(reshape2)
library(patchwork)
Sys.setlocale("LC_ALL","English")

```

## Aufgabe 1
### (a)

```{r}
dataraw<-read.csv("C:/Energieerzeugung_long_format.csv")

dataraw$date<-as.Date(dataraw$date,format="%d.%m.%Y")
head(dataraw)



dataraw1<-subset(dataraw,date=="2022-12-10" | date=="2022-08-01")




dataraw1$renewable<-NA
dataraw1$renewable[dataraw1$source %in%
                     c("Biomasse","Wasserkraft","Wind_Offshore","Wind_Onshore","Photovoltaik","Sonstige_Erneuerbare_Energien")]<-"renewable energy"

dataraw1$renewable[is.na(dataraw1$renewable)]<-"non-renewable energy"

dataraw1$source <-gsub("Wind_Offshore","Wind (Offshore)",dataraw1$source)
dataraw1$source <-gsub("Wind_Onshore","Wind (Onshore)",dataraw1$source)
dataraw1$source <-gsub("Sonstige_Erneuerbare_Energien","Sonstige erneuerbare Energien",dataraw1$source)
dataraw1$source <-gsub("Sonstige_Konventionelle_Energien","Sonstige konventionelle Energien",dataraw1$source)


ggplot(dataraw1,aes(x=source,y=energy,fill=renewable))+
  facet_grid(renewable~date,scales = "free_y")+
         geom_bar(stat="identity")+
  coord_flip()+
  scale_fill_manual(values=c("Red","Green"))+
  guides(fill=F)+
  labs(x="",y="Energieerzeugung in [MWh]")+
  scale_y_continuous(breaks=c(0,100000,200000,300000),labels = c("0","1000","2000","3000"))


```

### (b)

```{r}
dataraw$start<-NULL
dataraw$end<-NULL

dataraw2<-aggregate(dataraw[,3],by=list(date=dataraw$date,source=dataraw$source),mean)
names(dataraw2)[3]<-"energy"



dataraw2$renewable<-NA
dataraw2$renewable[dataraw2$source %in%
                     c("Biomasse","Wasserkraft","Wind_Offshore","Wind_Onshore","Photovoltaik","Sonstige_Erneuerbare_Energien")]<-"renewable energy"

dataraw2$renewable[is.na(dataraw2$renewable)]<-"non-renewable energy"



dataraw3<-aggregate(dataraw2[,3],by=list(date=dataraw2$date,renewable=dataraw2$renewable),sum)
names(dataraw3)[3]<-"energy"
head(dataraw3)


dataraw3$month<-substr(dataraw3$date,6,7)


ggplot(dataraw3,aes(x=month,y=energy,fill=renewable))+
  geom_boxplot(outlier.shape = 8)+
  scale_fill_manual(values=c("White","Blue"))+
  theme_minimal()+
  labs(title="Energy Production per month",y="Energy Production in [MWh]",x="Month")+
  scale_x_discrete(breaks=c("01","02","03","04","05","06","07","08","09","10","11","12"),
                   labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"))
         
       
```



